algoritmo "semnome"
// Função :
// Autor :
// Data : 22/03/2021
// Seção de Declarações
var
n ,c : inteiro
inicio
c <- 0
repita
   escreval(" ===============")
   escreval("|   M  E  N  U  |")
   escreval(" ===============")
   escreval("|  [1] De 1 a 10|")
   escreval("|  [2] De 10 a 1|")
   escreval("|  [3] Sair     |")
   escreval(" ===============")
   leia(n)
   escolha n
   caso 1
   c <- 1
   escreva(cont, "..")
   cont <- n+1
ate n = 3

fimalgoritmo
