algoritmo "semnome"
// Função :
// Autor :
// Data : 26/03/2021
// Seção de Declarações 
var
 v, i, x : inteiro
 
 procedimento nPerfect (t)
 var a,o inteiro
 inicio
 t / a = o
 se t/ a= o
 
 fimprocedimento
inicio
// Seção de Comandos 
escreva("Quantos valores voce vai digitar? ")
leia(v)
para i de 1 ate v faca
     escreva("Digite um valor: ")
     leia(x)
     nPerfect(i)


fimpara

fimalgoritmo
